/**
 *
 */
package com.ycsoft.commons.constants;

/**
 * @author liujiaqi
 *
 */
public enum DictKey {
	ACCTITEM_TYPE, ACCT_BALANCE, ACCT_CHANGE_TYPE, ACCT_FEE_TYPE, ACCT_PRESENT_TYPE,
	ACCT_TYPE, AREA, ATV_SERV_TYPE, BACK_TASK, BAND_BIND_TYPE, 
	BAND_CHECK_TYPE, BANK_CODE, BILLING_TYPE, BILLING_UNIT, 
	BOOLEAN, BUSI_BUY_MODE, BUSI_CODE, BUSI_PAY_TYPE, CARD_MODEL,
	CERT_TYPE, COUNTY, CUST_CLASS, CUST_COLONY, CUST_LEVEL, CUST_NET_TYPE,
	CUST_TYPE, C_CUST_DEVICE_STATUS, C_CUST_STATUS, C_FEE_ACCT_STATUS, 
	C_FEE_BUSI_STATUS, C_FEE_DEVICE_STATUS, C_PROD_STATUS, C_USER_STATUS,
	DEPOT, DEPOT_BUY_MODE, DEPT, DEPT_TYPE, DEVICE_BUY_MODE, DEVICE_BUY_TYPE, 
	DEVICE_OWNERSHIP, DEVICE_DIFF_TYPE, DEVICE_TYPE,OTHER_DEVICE_TYPE,ALL_DEVICE_TYPE, DTV_SERV_TYPE, EXTEND_TYPE,
	EXT_INPUT_TYPE, FEE_TYPE,FEE_TYPE_CFG, INDUSTRY, MODEM_MODEL, OPTR, 
	S_OPTR_STATUS, PAY_TYPE, PRINTITEM_NAME, PRINT_TYPE, PROD_TYPE, ROLE_TYPE, 
	RULE_DATE_CONSTANT, R_DEVICE_DEPOT_STATUS, R_DEVICE_DEVICE_STATUS, SERV_ID,
	SEX, STATUS, STB_DEFINITION, STB_MODEL,SUB_SYSTEM, STOP_TYPE, SYS_LEVEL, 
	TEMPLATE_TYPE, TERMINAL_TYPE, USER_LOGOFF_DOFEE, USER_LOGOFF_REASON, 
	USER_NET_TYPE, USER_PROD_ORDER_TYPE, USER_TYPE, DATA_TYPE,  DEVICE_TRAN_TYPE,	DEVICE_OUT_TYPE
	,DEVICE_TRAN_STATUS,INVOICE_STATUS,STATUS_R_INVOICE,INVOICE_TYPE,STATUS_P_PROD,STATUS_T_BUSI_FEE, USER_CLASS, INVOICE_MODE,TARIFF_TYPE, FITTING_MODEL,
	JOB_MESSAGE_TYPE,JOB_TASK_CODE,JOB_SEND_TYPE,INVOICE_OPTR_TYPE,CMD_TYPE,VALUABLE_CARD_TYPE,
	RES_TYPE,ADDRESS_UPDATE_TYPE,PUBLIC_ACCTITEM_TYPE,FUNC_CODE,MODEM_TYPE,PAY_TYPE_PRINT,TV_MODEL,
	PROJECT_STATUS,PROJECT_PROCESS,PROJECT_TYPE,SEPARATE_TYPE,ADJUST_REASON,CA_SUPPLIER,USER_LEIBIE,PROM_TYPE,VOD_USER_TYPE,
	FEE_BIG_TYPE,DEPT_BUSICODE,BUSI_CONFIRM,TASK_TYPE,STATUS_W_TASK,TASK_BUG_CAUSE,TASK_FAILURE_CAUSE,TASK_CREATE_TYPE,SATISFACTION,
	RECLAIM_REASON,TRANSFER_STATUS,OPTR_LOGIN
	/**设备更换原因**/
	,CHANGE_REASON
	/**代金券类型**/
	,VOUCHER_TYPE,
	/**OSD合法词组**/
	OSD_PHRASE,
	/**工单类型*/
	TASK_DETAIL_TYPE,
	/**汇率*/
	EXCHANGE,
	/**未支付取消费用提示*/
	UNPAY_CANCEL_PROMPT,
	/**地址门牌号的客户状态**/
	NOTE_STATUS_TYPE, AGENT,
	DEVICE_MODEL,
	/**订单支付类型**/
	ORDER_FEE_TYPE,
	/**工单完成类型**/
	TASK_FINISH_TYPE,
	/**开户服务语言**/
	LANGUAGE_TYPE,
	/**资费服务渠道**/
	SERVICE_CHANNEL,
	/**BUSI_FEE**/
	BUSI_FEE,ACCTITEM
}
