insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'SERVER_ID', 'DVN0100', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'SRC_TABLE', 'busi.j_ca_command', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'SRC_TABLE_BAK', 'busi.j_ca_command_day', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'DST_TABLE', 'busi.j_ca_command_out', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'DST_TABLE_BAK', 'busi.j_ca_command_out_bak', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'SEQ_DST_TRANSNUM', 'busi.seq_ca_transnum', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'ORDER_COUNT', '2', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'ORDER1', 'card_id=''1234''', null);
insert into BUSI.T_CA_INTERFACE (PROCESS_NAME, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, REMARK)
values ('G2', 'CA_SCHE', 'ORDER2', 'card_id<>''1234''', null);
commit;


insert into BUSI.T_SERVER_PARAMETER (SERVER_ID, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, STATUS, REMARK)
values ('DVN0100', 'CA_SCHE', 'CAS_TYPE', 'DVN', 'ZC', 'CA类型');
insert into BUSI.T_SERVER_PARAMETER (SERVER_ID, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, STATUS, REMARK)
values ('DVN0100', 'CA_SCHE', 'POOL', '100', 'ZC', ' 目标表未处理指令数量');
insert into BUSI.T_SERVER_PARAMETER (SERVER_ID, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, STATUS, REMARK)
values ('DVN0100', 'CA_SCHE', 'CAS_SQL', 'AND CAS_ID=''DVN0100''', 'ZC', 'SQL部分');
insert into BUSI.T_SERVER_PARAMETER (SERVER_ID, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, STATUS, REMARK)
values ('DVN0100', 'CA_SCHE', 'ADD_MODE', 'SAME_TIME', 'ZC', '时间相同');
insert into BUSI.T_SERVER_PARAMETER (SERVER_ID, PROGRAM_TYPE, PARA_NAME, PARA_VALUE, STATUS, REMARK)
values ('DVN0100', 'CA_SCHE', 'CANCEL_MODE', 'NOTSUPPORT', 'ZC', '不支持');
commit;

